### ISSUE TITLE
keep getting error Cannot find module 'yeoman-generator'

### ISSUE THREAD

**Issue by sd86** [Microsoft/generator-code#5]
I've install nvm and using version v0.12.7. The installation of yo, generator-code succeeds just fine. But everytime I run 'yo code', I get Cannot find module 'yeoman-generator'. Please help.

**Comment by chrisdias** [comment]
Hi - Sorry about this.  I've tried to reproduce the problem using nvm and node version 0.12.7 (as well as 0.10 and 0.12.0), but cannot.  What happens when you run "yo" from the terminal?  Does that work?  Can you install any other yeoman generators (for example, npm install -g generator-hottowel)?

**Comment by sd86** [comment]
I realized that yo was looking for the generators in the npm modules directory of the system installed node. I had started using nvm and switched to v0.12.0 but yo would still look for npm modules at the wrong place. I am not sure how it was getting to that path but I fixed the issue by simply deleting the system node's modules directory. Please let me know how the node module paths are resolved and where they live. Thank you for looking into this. I'm new to node, just started learning.

**Comment by chrisdias** [comment]
ok, glad you found a workaround. i'm not too familiar with nvm, but their docs at https://github.com/creationix/nvm discuss how packages are handled for different versions.
