### ISSUE TITLE
selecting typescript version

### ISSUE THREAD

**Issue by jefferyasharp** [Microsoft/generator-code#9]
for some reason I cant select the typescript version. I try the arrow keys and they do not work. I can only generate a pure javascript version

**Comment by JSMike** [comment]
I'm having the same issue on Windows 10. The arrow keys aren't registering in both cmd and git bash.

**Comment by chrisdias** [comment]
we are going to repurpose this generator towards creating extensions for VS Code.  for the typescript and javascript applications that were created by this generator, you can download them from here: https://github.com/Microsoft/vscode-samples.git.  remember to run npm install in the folder before running the app.
